/**
 * Test Phase 4.6: Video Generator + Storyboard
 */
const path = require('path');

async function testVideoGenerator() {
    console.log('═══ Testing Video Generator ═══\n');

    const { generateVideo, cleanupBrowser, SLIDE_RENDERERS, TRANSITIONS } = require('./scripts/video-generator.js');

    console.log(`Slide renderers: ${Object.keys(SLIDE_RENDERERS).length} types`);
    console.log(`Transitions: ${Object.keys(TRANSITIONS).join(', ')}\n`);

    // Test 1: Short video with storyboard (3 slides, 2s each = 6s)
    console.log('Test 1: Short video with storyboard...');
    try {
        const result = await generateVideo({
            title: 'SDK-Overview-Video',
            theme: 'modern-blue',
            transition: 'fade',
            durationPerSlide: 2,
            storyboard: true,
            sections: [
                { type: 'title', text: 'Document Generation SDK', subtitle: 'Award-Winning Outputs', author: 'DocGenie' },
                { type: 'bullets', title: 'Supported Formats', items: ['PowerPoint (28 slide types)', 'Word (18 section types)', 'PDF (watermark, TOC, borders)', 'HTML (dark mode, search)', 'Infographic PNG (5 templates)', 'Markdown (GFM, Mermaid)', 'Video (WebM, experimental)'] },
                { type: 'closing', text: 'Thank You', subtitle: 'Generated by the Award-Winning SDK' },
            ],
        });

        console.log(`  Success: ${result.success}`);
        console.log(`  File: ${result.fileName}`);
        console.log(`  Size: ${result.fileSizeHuman}`);
        console.log(`  Duration: ${result.duration}`);
        console.log(`  Slides: ${result.slideCount}`);
        console.log(`  Transition: ${result.transition}`);
        if (result.storyboardDir) {
            const fs = require('fs');
            const pngs = fs.readdirSync(result.storyboardDir).filter(f => f.endsWith('.png'));
            console.log(`  Storyboard: ${pngs.length} PNGs in ${path.basename(result.storyboardDir)}/`);
        }
    } catch (err) {
        console.log(`  ERROR: ${err.message}`);
    }

    // Test 2: Different transition (zoom, no storyboard)
    console.log('\nTest 2: Zoom transition, metric slide...');
    try {
        const result = await generateVideo({
            title: 'Metrics-Video',
            theme: 'dark-professional',
            transition: 'zoom',
            durationPerSlide: 3,
            storyboard: false,
            sections: [
                { type: 'title', text: 'Project Metrics', subtitle: 'Q1 2026 Report' },
                { type: 'metric-strip', title: 'Key Numbers', metrics: [{ label: 'Tools', value: '35' }, { label: 'Formats', value: '7' }, { label: 'Score', value: 'A+' }] },
                { type: 'callout', variant: 'success', title: 'All Tests Passing', content: '6/6 SDK tool tests verified and operational.' },
                { type: 'closing', text: 'End of Report' },
            ],
        });

        console.log(`  Success: ${result.success}`);
        console.log(`  Size: ${result.fileSizeHuman}`);
        console.log(`  Duration: ${result.duration}`);
        console.log(`  Transition: ${result.transition}`);
    } catch (err) {
        console.log(`  ERROR: ${err.message}`);
    }

    await cleanupBrowser();
    console.log('\n═══ Video Generator Tests Complete ═══');
}

testVideoGenerator().catch(console.error);
